# Site settings
title: Immanuel Bible Church
email: glossa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official website of Immanuel Bible Church in Santa Monica, CA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ibcbible.org" # the base hostname & protocol for your site
twitter_username: ibcbible
github_username:  ibcbible

# Build settings
markdown: kramdown

highlighter: rouge